# Generated by Django 5.1.3 on 2024-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_entitlement',
            field=models.IntegerField(default=15),
        ),
    ]
